### ISSUE TITLE
Support multiple ReplyUrls from a single Release variable

### ISSUE THREAD

**Issue by wouterroos** [LockTar/AzureAdApplicationManagement#14]
Hi, 

Currently, specifying multiple ReplyUrls seems to require some kind of newline separated list (see image below).

![image](https://user-images.githubusercontent.com/5137829/47496368-e5439a00-d856-11e8-8d73-63c2840c5af8.png)

It would however be convenient to supply a single Release variable that contains multiple reply url's (use case: provide both a 'mydomain.com' and 'www.mydomain.com' reply url) in a single Release variable. This could be achieved by defining a separator (e.g. ',' or ';') between reply urls and split the input string based on that separator.

Thanks in advance,

Regards,
Wouter

**Comment by LockTar** [comment]
Option added in v2 of the "Set" task

**Comment by wouterroos** [comment]
@LockTar Thanks, I see the new version in DevOps. Though it seems that the **Azure Connection Type** and **Azure Subscription** fields have dissapeared in this version, is this by design?

**Comment by LockTar** [comment]
@wouterroos the Azure Connection Type should only been disappeared. I just checked it and your right. Created new issue for this #22
