### ISSUE TITLE
Azure Subscription field for connection missing in tasks

### ISSUE THREAD

**Issue by LockTar** [LockTar/AzureAdApplicationManagement#22]
The connection dropdown to Azure is missing in the v2 task.

**Comment by LockTar** [comment]
@wouterroos this seems only be happening in pipelines that already have been created **before** v2 was released. Even new tasks (automatically v2) in that existing pipeline have that problem. No idea what the issue is. 

But I will make a fix for this.

**Comment by LockTar** [comment]
Found the cause of the problem. Only made the change in the 'Get' task and not in the other 3 tasks. Get was working fine. Now all 4 tasks should work fine. Tested it with my own pipeline.

**Comment by wouterroos** [comment]
@LockTar Thanks, all seems to work now, will test tomorrow.
