### ISSUE TITLE
Add ability to grant permissions on the 'Set' action

### ISSUE THREAD

**Issue by glloyd2010f** [LockTar/AzureAdApplicationManagement#27]
When running the set task have the ability to grant permission for the App Registration. An example of this can be found here.

https://stackoverflow.com/questions/48556167/how-to-give-grant-permissions-for-an-app-in-azure-ad-using-powershell

**Comment by LockTar** [comment]
Hi, good question.
I think this code is possible but it isn't official code of Microsoft. The url that the script is calling, is used by the Azure portal when you click on the button. I'm not really a fan of implementing this when it can change any moment....

Then, even if this was official code, your service principal that is executing the task (service connection in Azure DevOps/VSTS) must be a Global Administrator of your tenant... There is no other way to do this at this moment.
In the future Microsoft is adding functionality to do this in a better way.

Any other thoughts about this?

**Comment by LockTar** [comment]
Closing because is not using native Azure functionality
