### ISSUE TITLE
Both New Azure AD Application and Set Azure AD Application fail

### ISSUE THREAD

**Issue by rogeratcloudiscode** [LockTar/AzureAdApplicationManagement#31]
I tried to use the extension but it always fails with the following error message:
##[error]Invalid value specified for property 'replyUrls' of resource 'Application'.

I have tried, for example passing one of these, using both version 1 and 2, using simple or multiple line field for Reply URLs, using either variables or passing the explicit value, between quotes and without quotes:
https://cms-test.roger.eu/sitecore
https://cms-test.roger.eu
cms-test.roger.eu
cms-test.roger.eu/sitecore

None of them work.

**Comment by LockTar** [comment]
Hi, That's strange. The first two looks fine. It should start with https. You should not use quotes and you can use a variable.

Can you please test if it works when you use in example https://Microsoft.com? I can't test it myself because of holiday.
