### ISSUE TITLE
How to setup the tasks with the new App registration that we have created

### ISSUE THREAD

**Issue by kdharma** [LockTar/AzureAdApplicationManagement#34]
Hi there, sorry this might be silly question but I'm not really understand or clear regarding the steps in the Getting Started section. So I have create/register new app that has permission to manage application and also read directory. When I created the pipeline and see all of your tasks, I do not see any option where I can configure it to use the new App information that I just created. How can your tasks knows or use the new App that I just created and have permission to create or set an Azure AD Application?

**Comment by LockTar** [comment]
> So I have create/register new app that has permission to manage application and also read directory.

You also got the admin consent from the administrator?

> When I created the pipeline and see all of your tasks, I do not see any option where I can configure it to use the new App information that I just created. How can your tasks knows or use the new App that I just created and have permission to create or set an Azure AD Application?

Your `Azure Subscription` field (the connection from Azure DevOps to your Azure subscribtion) is running under a service principal/application (step 1). 
You need to set the permission on that application. You can get the applicationid/clientid when you go to "Service connections" in your ADO project settings. (Steps 2-7).

**Comment by kdharma** [comment]
Got it to work @LockTar , thanks. Apparently I need to configure the service endpoint app registration that gets created when I create a new service endpoints.
