### ISSUE TITLE
Add ability to set Oauth2AllowImplicitFlow 

### ISSUE THREAD

**Issue by kdharma** [LockTar/AzureAdApplicationManagement#36]
Add capability to configure OAuth2.0 implicit flow tokens. Setting OAuth2.0 implicit flow tokens is part of [Set-AzureADApplication](https://docs.microsoft.com/en-us/powershell/module/azuread/set-azureadapplication?view=azureadps-2.0) command (-Oauth2AllowImplicitFlow ).

Sample script:
`Set-AzureADApplication -ObjectId {objectid} -Oauth2AllowImplicitFlow {$true or $false}`

**Comment by LockTar** [comment]
I thought the default is false right?

**Comment by kdharma** [comment]
Yes you are correct. The default is false

**Comment by LockTar** [comment]
Added. Can be tested.

**Comment by kdharma** [comment]
Hi @LockTar , I have tested the new capabilities and it works. Thank you so much for your support.
