### ISSUE TITLE
ConnectedServiceNameARM uses wrong value

### ISSUE THREAD

**Issue by helmerm** [LockTar/AzureAdApplicationManagement#40]
I am using the `Set-Azure-AD-Application` task in a template and the ConnectedServiceNameARM is set via template parameter. I have two ARM service connections configured on the project. When the task is executed, the wrong service connection (not the one defined via parameter) is used which causes a permission error. The parameter is set to a variable coming from a variable group.

![image](https://user-images.githubusercontent.com/3226548/79984726-dec4cb80-84a9-11ea-9a54-f16c70d12eea.png)

In order to debug this issue, I have added a `script` task before, which prints the parameter and shows the correct value. Something is causing the `ConnectedServiceNameARM` input to be wrong.

The `Azure resource group deployment` task seems to work with the variable.
I could not spot what is causing the behavior yet. Do you have any hints?

**Comment by LockTar** [comment]
Not sure... but can [this](https://github.com/microsoft/azure-pipelines-agent/issues/1307) be the problem? Not sure if connection in parameter works? I thought I had this problem as well and it didn't work..

**Comment by helmerm** [comment]
Yes, I am using variable groups and it works if hard-coded, but not coming from the variable group.

Seems to work for the Microsoft tasks (App service deploy). I will try to see if there is a difference in the task implementation. Maybe something special about how the VSTS SDK reads the parameters?

**Comment by LockTar** [comment]
I think so. If you can find something then I will fix right away.
