### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by vara-incresol** [LockTar/AzureAdApplicationManagement#41]
Hi,

I got the issue 'Resource Not Found For The Segment' and followed all settings w.r.t permissions and Service connections. Though the issue appeared. Could you please help me on this.

I am attaching the log file here.
[logs_165.zip](https://github.com/LockTar/AzureAdApplicationManagement/files/4823711/logs_165.zip)

_Originally posted by @abdulkareem-incresol in https://github.com/LockTar/AzureAdApplicationManagement/issues/38#issuecomment-648636379_

**Comment by LockTar** [comment]
Is this the same issue as the comment in #38 or the same type? So are you two in the same team?

**Comment by LockTar** [comment]
At the moment I'm not able to open zip. Could you describe what is going wrong? Also put the last few commands of the log in here?
Is this an existing app registration or new one? Does the extension create something or completely nothing?

**Comment by vara-incresol** [comment]
Hi,

Issue raised in #38 is from other person. Myself and the person who made last comment over there belong to same team.

Anyways, let me share you the error trace. PFB:

##[debug]Evaluating condition for step: 'Create New Azure AD Application'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
Starting: Create New Azure AD Application
==============================================================================
Task         : New Azure AD Application
Description  : Create a new Azure AD Application
Version      : 2.0.27
Author       : Ralph Jansen
Help         : Task version: 1.2.27
==============================================================================
##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
##[debug]Entering D:\a\_tasks\New-Azure-AD-Application_3d116dd1-d4bd-53f0-b6f3-cb9a511d911f\2.0.27\Main.ps1.
##[debug]INPUT_NAME: 'ng-node-test'
##[debug]INPUT_SIGNONURL: 'https://ng-node-test.azurewebsites.net'
##[debug]INPUT_APPIDURI (empty)
##[debug]Loading module from path 'D:\a\_tasks\New-Azure-AD-Application_3d116dd1-d4bd-53f0-b6f3-cb9a511d911f\2.0.27\ps_modules\VstsAzureHelpers\VstsAzureHelpers.psm1'.
##[debug]$OVERRIDING $global:DebugPreference from 'Continue' to 'SilentlyContinue'.
##[debug]Exporting function 'Initialize-AzureRM'.
##[debug]Exporting function 'Initialize-AzureAD'.
##[debug]Exporting function 'Initialize-PackageProvider'.
##[debug]Exporting function 'Initialize-Module'.
##[debug]Importing function 'Initialize-AzureAD'.
##[debug]Importing function 'Initialize-AzureRM'.
##[debug]Importing function 'Initialize-Module'.
##[debug]Importing function 'Initialize-PackageProvider'.
##[debug]Initialize package provider NuGet
[ad_app_error_trace.txt](https://github.com/LockTar/AzureAdApplicationManagement/files/4840339/ad_app_error_trace.txt)

**Comment by LockTar** [comment]
I see you are using the "New" task. Could you try the "Set" task? That is the preferred way. You have an option in that task to create the app registration if none exists. 

Could you answer the following questions:

1. Is this an existing app registration (created without this extension) or a new one? 
2. Does the extension create something (do you see something in Azure?) or completely nothing?
3. Has the service principal been granted for the permissions as described in the [get started](https://github.com/LockTar/AzureAdApplicationManagement#get-started)? Most important step 6 and 7!

**Comment by LockTar** [comment]
I know almost for sure that it is the permissions for the service connection (service principal of the agent). So step 6 and 7 of the getting started.

**Comment by LockTar** [comment]
I think I see the issue. I see as permissions the "Microsoft Graph" api in the screenshot which is the new way to do things with the Azure AD. Only not everything is ported yet so we still need to use the old Azure Active directory api. 

If you look at the getting started you will see the permissions of the old api. You can compare it with your manifest. If you want, you can copy the getting started permissions and add them to your current array or overwrite your current permissions. Of course you will need to ask admin consent for the new permission again.

**Comment by abdulkareem-incresol** [comment]
Hi,

Thank you so much for your prompt replies. I will try this and update if the problem gets resolved.

**Comment by LockTar** [comment]
and?
